# Site settings
title: GPQuery by Joho - GitHub Pages
email: joho@joho.us
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gpquery.github.io" # the base hostname & protocol for your site
github_username:  loljoho

# Global Configuration

# Build settings
markdown: kramdown

# GitHub Flavoured Markdown Recognition
kramdown: 
  input: GFM

# Syntax highlighting
#highlighter: rouge
highlighter: pygments

# For additional configuration parameters and details, see:
# https://pages.github.com/versions/
# http://jekyllrb.com/docs/configuration
